<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Broiler.CSS" Version="0.1.0-preview.2" />
    <PackageVersion Include="Broiler.Dom.Html" Version="0.1.0-preview.2" />
    <PackageVersion Include="Broiler.Graphics" Version="0.1.0-preview.3" />
    <PackageVersion Include="Broiler.Graphics.Windows" Version="0.1.0-preview.3" />
    <PackageVersion Include="Broiler.Layout" Version="0.1.0-preview.2" />
    <PackageVersion Include="Broiler.Media.Image.Managed" Version="0.1.0-preview.11" />
  </ItemGroup>
</Project>
