using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// Title, company, copyright and the versions are generated by the SDK from the package
// metadata, so every assembly carries the preview version it was packed with.
[assembly: ComVisible(false)]
[assembly: InternalsVisibleTo("Broiler.HTML.Core")]
[assembly: InternalsVisibleTo("Broiler.HTML.Image.Compat")]
